<?php

/**
 * @file
 * Ejercicio básico para la capacitación.
 */

/**
 * Implements hook_theme().
 */
function ejercicio_theme($existing, $type, $theme, $path) {
  return array(
    'ejercicio_ultimos_nodos' => array(
      'template' => 'ejercicio-ultimos-nodos',
      'variables' => array(
        'cantidad' => NULL,
        'tipo' => NULL,
        'titulos' => array(),
      ),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ejercicio_menu() {
  $items['admin/config/system/ejercicio'] = array(
    'title' => 'Opciones de ejercicio',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ejercicio_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ejercicio.pages.inc',
  );

  return $items;
}


/**
 * Implements hook_block_info().
 */
function ejercicio_block_info() {
  $bloques = variable_get('ejercicio_cantidad_de_bloques', 1);
  $bloques = intval($bloques);
  $blocks = array();
  for ($i = 0; $i < $bloques; ++$i) {
    $blocks[$i] = array(
      'info' => t('Bloque de ejercicio @index', array('@index' => $i + 1)),
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ejercicio_block_view($delta = '') {
  $tipos = node_type_get_names();
  $cantidad = variable_get('ejercicio_cantidad_' . $delta, 5);
  $tipo = variable_get('ejercicio_tipo_' . $delta, NULL);

  if ($tipo) {
    $nodos = _ejercicio_get_nodos($cantidad, $tipo);
    return array(
      'subject' => t('Hola mundo'),
      'content' => theme('ejercicio_ultimos_nodos', array('cantidad' => $cantidad, 'tipo' => $tipos[$tipo], 'titulos' => $nodos)),
    );
  }
}

/**
 * Implements hook_block_save().
 */
function ejercicio_block_save($delta = '', $edit = array()) {
  variable_set('ejercicio_cantidad_' . $delta, $edit['cantidad']);
  variable_set('ejercicio_tipo_' . $delta, $edit['tipo']);
}

/**
 * Implements hook_block_configure().
 */
function ejercicio_block_configure($delta = '') {
  $form['cantidad'] = array(
    '#type' => 'textfield',
    '#title' => t('Cantidad'),
    '#description' => t('Seleccionar la cantidad de nodos a mostrar'),
    '#size' => 4,
    '#default_value' => variable_get('ejercicio_cantidad_' . $delta, 5),
  );
  $form['tipo'] = array(
    '#type' => 'select',
    '#title' => t('Tipo de contenido'),
    '#description' => t('Seleccionar el tipo de contenido a mostrar'),
    '#options' => node_type_get_names(),
    '#empty_option' => t('- Seleccionar -'),
    '#empty_value' => '',
    '#default_value' => variable_get('ejercicio_tipo_' . $delta, ''),
  );

  return $form;
}

function _ejercicio_get_nodos($cantidad, $tipo) {
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->orderBy('created', 'DESC')
    ->range(0, intval($cantidad));

  if ($tipo) {
    $query->condition('n.type', $tipo);
  }

  $nodos = $query->execute();
  $links = array();
  foreach ($nodos as $nodo) {
    $links[] = l($nodo->title, 'node/' . $nodo->nid, array('absolute' => TRUE));
  }

  return $links;
}
